name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build site
        run: |
          # Your build commands here
          echo "Site built successfully"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public # Adjust this to your build output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
